services:
  backend:
    image: aragawmebratu/lms-backend:${BACKEND_IMAGE_TAG}
    ports:
      - "8000:8000"

  frontend:
    image: aragawmebratu/lms-frontend:${FRONTEND_IMAGE_TAG}
    ports:
      - "80:80"
